// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//         http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Description:
// This pipeline builds the `voltron-demo` (CARLA 0.9.15, SOME/IP bridge, AAOS 26Q2 dev tools)
// Docker image for use in GCP Cloud Workstations.
// Pipeline uses BuildKit to avoid docker-in-docker privilege issues.

pipeline {
  agent none

  environment {
    REGISTRY="${env.CLOUD_REGION}-docker.pkg.dev"
    IMAGE_NAME="${env.CLOUD_WS_HORIZON_VOLTRON_DEMO_IMAGE_NAME ?: "sdv-images/voltron-demo"}"
    DESTINATION="${REGISTRY}/${env.CLOUD_PROJECT}/${IMAGE_NAME}"
    PUSH="${NO_PUSH == "true" ? "false" : "true"}"
    HORIZON_DOMAIN="${env.HORIZON_DOMAIN}"
    GOOGLE_CLOUD_PROJECT="${env.CLOUD_PROJECT}"

    def kubernetesPodTemplate = """
      apiVersion: v1
      kind: Pod
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        labels:
          cloud_ws_voltron_demo_build_pod: "true"
      spec:
        tolerations:
          - key: workloadType
            operator: Equal
            value: android
            effect: "NoSchedule"
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: aaos_pod
                  operator: Exists
              topologyKey: kubernetes.io/hostname
            - labelSelector:
                matchExpressions:
                - key: cloud_ws_voltron_demo_build_pod
                  operator: Exists
              topologyKey: kubernetes.io/hostname
        hostname: jenkins-cloud-ws-voltron-demo-build-pod
        serviceAccountName: ${JENKINS_SERVICE_ACCOUNT}
        containers:
        - name: buildkit
          image: moby/buildkit:${BUILDKIT_RELEASE_TAG}
          imagePullPolicy: Always
          securityContext:
            privileged: true
          resources:
            limits:
              cpu: 98000m
              memory: 180000Mi
            requests:
              cpu: 98000m
              memory: 180000Mi
        nodeSelector:
          workloadLabel: android
    """.stripIndent()
  }

  stages {
    stage ('Start instance'){
      agent { kubernetes { yaml kubernetesPodTemplate } }
      stages {
        stage ('Docker Credentials'){
          steps {
            script {
              currentBuild.description = "NO_PUSH=${env.NO_PUSH}" + "<br>" + "$BUILD_USER"
            }
            container(name: 'buildkit') {
              catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                sh '''
                  wget -nv -O docker-credential-gcr.tgz ${DOCKER_CREDENTIALS_URL}
                  tar -zxf docker-credential-gcr.tgz
                  chmod +x docker-credential-gcr && mv docker-credential-gcr /usr/bin/
                  rm -f docker-credential-gcr*.tar.gz
                  docker-credential-gcr configure-docker --registries=${REGISTRY}
                '''
              }
            }
          }
        }

        stage ('Build Docker Image'){
          when { expression { env.IMAGE_TAG } }
          steps {
            container(name: 'buildkit') {
              catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                sh '''
                  cd "${WORKSPACE}/workloads/cloud-workstations/pipelines/workstation-images/voltron-demo/";
                  if [ -d "${WORKSPACE}/workloads/cloud-workstations/pipelines/workstation-images/common-utils/" ]; then
                    cp -r "${WORKSPACE}/workloads/cloud-workstations/pipelines/workstation-images/common-utils/" ./common-utils/;
                  fi
                  buildctl build \
                   --frontend=dockerfile.v0 \
                   --local dockerfile=. \
                   --local context=. \
                   --opt platform=linux/amd64 \
                   --opt build-arg:HORIZON_DOMAIN=${HORIZON_DOMAIN} \
                   --opt build-arg:GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT} \
                   --registry-auth-tlscontext host=${REGISTRY},insecure=true \
                   --output=type=image,name=${DESTINATION}:${IMAGE_TAG},push=${PUSH}
                '''
              }
            }
          }
        }
      }
    }
  }
}
