#!/bin/bash
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

echo "Welcome to the aaos-sdv dev env!"
if [ -f /google/sdv-utils/README ]; then
    echo '"cat /google/sdv-utils/README" to get started'

# fn for launching carla in a standalone terminal
launch_carla() {
    gnome-terminal -- bash -ic 'trap exit SIGINT; /google/someip-bridge/run_carla_and_bridge.sh --mode=manual-wasd; exec bash'
}

# source cvd-wrapping utils
if [ -f /google/aaos-utils/dev_utils.sh ]; then
    source /google/aaos-utils/dev_utils.sh
fi
