apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.namespacePrefix }}landingpage-html
  namespace: {{ .Values.config.namespacePrefix }}horizon
data:
  index.html: |
{{ .Files.Get "files/index.html" | indent 4 }}
