# Copyright (c) 2026 Accenture, All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if .Values.config.gatewayTunnel.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.config.namespacePrefix }}gateway-tunnel
  namespace: {{ .Values.config.namespacePrefix }}gke-gateway
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-tunnel
  template:
    metadata:
      labels:
        app: gateway-tunnel
    spec:
      hostNetwork: true
      tolerations:
      - operator: Exists
      containers:
      - name: socat
        image: alpine/socat:1.8.0.0
        args: ["-d", "-d", "TCP-LISTEN:18080,fork,reuseaddr", "TCP:{{ .Values.config.gatewayTunnel.targetIp }}:80"]
        ports:
        - containerPort: 18080
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.config.namespacePrefix }}gateway-tunnel
  namespace: {{ .Values.config.namespacePrefix }}gke-gateway
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    app: gateway-tunnel
  ports:
  - port: 80
    targetPort: 18080
{{- end }}
