# Copyright (c) 2024-2026 Accenture, All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: headlamp-route
  namespace: {{ .Values.config.namespacePrefix }}headlamp
  labels:
    gateway: gke-gateway
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  parentRefs:
    - kind: Gateway
      name: gke-gateway
      namespace: {{ .Values.config.namespacePrefix }}gke-gateway
      sectionName: http
  hostnames:
    -  {{ .Values.config.domain }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /headlamp/
      filters:
        - type: URLRewrite
          urlRewrite:
            hostname:  {{ .Values.config.domain }}
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /headlamp/
      backendRefs:
        - name: {{ .Values.config.namespacePrefix }}headlamp-oauth2-proxy
          port: 80
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: headlamp-healthcheck
  namespace: {{ .Values.config.namespacePrefix }}headlamp
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  default:
    checkIntervalSec: 15
    timeoutSec: 15
    healthyThreshold: 1
    unhealthyThreshold: 2
    logConfig:
      enabled: true
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_SERVING_PORT
        requestPath: /ping
        host: {{ .Values.config.domain }}
  targetRef:
    group: ""
    kind: Service
    name: {{ .Values.config.namespacePrefix }}headlamp-oauth2-proxy
---
# Allow OAuth2 Proxy ingress from Gateway
{{- if .Values.config.enableNetworkPolicies }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-oauth2-proxy-ingress-from-gateway
  namespace: {{ .Values.config.namespacePrefix }}headlamp
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: oauth2-proxy
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - protocol: TCP
      port: 80     # HTTP traffic
    - protocol: TCP
      port: 4180   # OAuth2 proxy
    - protocol: TCP
      port: 44180  # Token injector

{{- end }}