# Copyright (c) 2024-2026 Accenture, All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.config.namespacePrefix }}headlamp-oauth2-proxy
  namespace: {{ .Values.config.namespacePrefix }}argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: {{ .Values.config.namespacePrefix }}horizon-sdv
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: {{ .Values.config.namespacePrefix }}headlamp-oauth2-proxy
      namespace: {{ .Values.config.namespacePrefix }}headlamp
      jsonPointers:
        - /data
  source:
    chart: oauth2-proxy
    repoURL: https://oauth2-proxy.github.io/manifests
    targetRevision: 8.3.0
    helm:
      values: |
        config:
          clientID: "oauth2-headlamp"

        extraArgs:
          provider: "oidc"
          oidc-issuer-url: "{{ .Values.config.ingress.scheme }}://{{ .Values.config.domain }}/auth/realms/horizon"
          redirect-url: "{{ .Values.config.ingress.scheme }}://{{ .Values.config.domain }}/headlamp/oauth2/callback"
          cookie-secure: "true"
          cookie-samesite: "lax"
          scope: "openid profile email roles"
          upstream: "http://{{ .Values.config.namespacePrefix }}headlamp-token-injector.{{ .Values.config.namespacePrefix }}headlamp.svc.cluster.local:8080/"
          http-address: "0.0.0.0:4180"
          pass-user-headers: "true"
          pass-authorization-header: "false"
          set-xauthrequest: "true"
          allowed-group: "administrators"
          oidc-groups-claim: "roles"
          skip-jwt-bearer-tokens: "false"
          skip-provider-button: "true"
          cookie-expire: "2h"
          email-domain: "*"
          proxy-prefix: "/headlamp/oauth2"
          cookie-path: "/headlamp"
          reverse-proxy: "true"

        extraEnv:
          - name: OAUTH2_PROXY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ .Values.config.namespacePrefix }}headlamp-oauth2-proxy
                key: client-secret
          - name: OAUTH2_PROXY_COOKIE_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ .Values.config.namespacePrefix }}headlamp-oauth2-proxy
                key: cookie-secret

        service:
          enabled: true
          type: ClusterIP
          portNumber: 80
          targetPort: 4180
          portName: http
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.config.namespacePrefix }}headlamp
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
---
# Allow OAuth2 Proxy to access Keycloak
{{- if .Values.config.enableNetworkPolicies }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-headlamp-oauth2-proxy-egress-to-keycloak
  namespace: {{ .Values.config.namespacePrefix }}headlamp
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: oauth2-proxy
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Values.config.namespacePrefix }}keycloak
      podSelector:
        matchLabels:
          app.kubernetes.io/name: keycloakx
    ports:
    - protocol: TCP
      port: 8080   # OAuth/OIDC

{{- end }}
---
# Allow OAuth2 Proxy to access Token Injector
{{- if .Values.config.enableNetworkPolicies }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-oauth2-proxy-egress-to-token-injector
  namespace: {{ .Values.config.namespacePrefix }}headlamp
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: oauth2-proxy
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ .Values.config.namespacePrefix }}headlamp-token-injector
    ports:
    - protocol: TCP
      port: 8080   # Token injector
{{- end }}
---
# Allow OAuth2 Proxy internet egress (for OIDC Discovery)
{{- if .Values.config.enableNetworkPolicies }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-headlamp-oauth2-proxy-egress-to-internet
  namespace: {{ .Values.config.namespacePrefix }}headlamp
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: oauth2-proxy
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 169.254.169.254/32
    ports:
    - protocol: TCP
      port: 443    # HTTPS
    - protocol: TCP
      port: 80     # HTTP

{{- end }}