# Copyright (c) 2024-2026 Accenture, All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak-writer-sa
  namespace: {{ .Values.config.namespacePrefix }}keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "4"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keycloak-writer-role
  namespace: {{ .Values.config.namespacePrefix }}keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "3"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keycloak-writer-rolebinding
  namespace: {{ .Values.config.namespacePrefix }}keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "4"
subjects:
  - kind: ServiceAccount
    name: keycloak-writer-sa
roleRef:
  kind: Role
  name: keycloak-writer-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.config.namespacePrefix }}keycloak-cluster-writer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: keycloak-writer-sa
    namespace: {{ .Values.config.namespacePrefix }}keycloak
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.config.namespacePrefix }}keycloak-post-mtk-connect-job
  namespace: {{ .Values.config.namespacePrefix }}keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/hook: Sync
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 120
  activeDeadlineSeconds: 600
  template:
    spec:
      serviceAccountName: keycloak-writer-sa
      containers:
        - name: keycloak-post-mtk-connect-container
          env:
            - name: NAMESPACE_PREFIX
              value: {{ .Values.config.namespacePrefix }}
            - name: PLATFORM_URL
              value: http://{{ .Values.config.namespacePrefix }}keycloak-keycloakx-http:8080
            - name: DOMAIN
              value: http://{{ .Values.config.domain }}
            - name: KEYCLOAK_USERNAME
              value: "admin"
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-initial-creds
                  key: password
          image: {{ .Values.config.postjobs.keycloakmtkconnect }}
          imagePullPolicy: Always
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.config.namespacePrefix }}keycloak-post-jenkins-job
  namespace: {{ .Values.config.namespacePrefix }}keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/hook: Sync
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 120
  activeDeadlineSeconds: 600
  template:
    spec:
      serviceAccountName: keycloak-writer-sa
      containers:
        - name: keycloak-post-jenkins-container
          env:
            - name: NAMESPACE_PREFIX
              value: {{ .Values.config.namespacePrefix }}
            - name: PLATFORM_URL
              value: http://{{ .Values.config.namespacePrefix }}keycloak-keycloakx-http:8080
            - name: DOMAIN
              value: http://{{ .Values.config.domain }}
            - name: KEYCLOAK_USERNAME
              value: "admin"
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-initial-creds
                  key: password
            - name: JENKINS_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-jenkins-admin
                  key: username
            - name: JENKINS_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-jenkins-admin
                  key: password
          image: {{ .Values.config.postjobs.keycloakjenkins }}
          imagePullPolicy: Always
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.config.namespacePrefix }}keycloak-post-headlamp-job
  namespace: {{ .Values.config.namespacePrefix }}keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/hook: Sync
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 120
  activeDeadlineSeconds: 600
  template:
    spec:
      serviceAccountName: keycloak-writer-sa
      containers:
        - name: keycloak-post-headlamp-container
          env:
            - name: NAMESPACE_PREFIX
              value: {{ .Values.config.namespacePrefix }}
            - name: PLATFORM_URL
              value: http://{{ .Values.config.namespacePrefix }}keycloak-keycloakx-http:8080
            - name: DOMAIN
              value: http://{{ .Values.config.domain }}
            - name: KEYCLOAK_USERNAME
              value: "admin"
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-initial-creds
                  key: password
          image: {{ .Values.config.postjobs.keycloakheadlamp }}
          imagePullPolicy: Always
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.config.namespacePrefix }}keycloak-post-argocd-job
  namespace: {{ .Values.config.namespacePrefix }}keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/hook: Sync
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 120
  activeDeadlineSeconds: 600
  template:
    spec:
      serviceAccountName: keycloak-writer-sa
      containers:
        - name: keycloak-post-argocd-container
          env:
            - name: NAMESPACE_PREFIX
              value: {{ .Values.config.namespacePrefix }}
            - name: PLATFORM_URL
              value: http://{{ .Values.config.namespacePrefix }}keycloak-keycloakx-http:8080
            - name: DOMAIN
              value: http://{{ .Values.config.domain }}
            - name: KEYCLOAK_USERNAME
              value: "admin"
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-initial-creds
                  key: password
            - name: ARGOCD_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-argocd-admin
                  key: username
            - name: ARGOCD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-argocd-admin
                  key: password
          image: {{ .Values.config.postjobs.keycloakargocd }}
          imagePullPolicy: Always
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.config.namespacePrefix }}keycloak-post-gerrit-job
  namespace: {{ .Values.config.namespacePrefix }}keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "7"
    argocd.argoproj.io/hook: Sync
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 120
  activeDeadlineSeconds: 600
  template:
    spec:
      serviceAccountName: keycloak-writer-sa
      containers:
        - name: keycloak-post-gerrit-container
          env:
            - name: NAMESPACE_PREFIX
              value: {{ .Values.config.namespacePrefix }}
            - name: PLATFORM_URL
              value: http://{{ .Values.config.namespacePrefix }}keycloak-keycloakx-http:8080
            - name: DOMAIN
              value: http://{{ .Values.config.domain }}
            - name: KEYCLOAK_USERNAME
              value: "admin"
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-initial-creds
                  key: password
            - name: GERRIT_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-gerrit-admin
                  key: username
            - name: GERRIT_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-gerrit-admin
                  key: password
          image: {{ .Values.config.postjobs.keycloakgerrit }}
          imagePullPolicy: Always
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.config.namespacePrefix }}keycloak-post-grafana-job
  namespace: {{ .Values.config.namespacePrefix }}keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "6"
    argocd.argoproj.io/hook: Sync
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 120
  activeDeadlineSeconds: 600
  template:
    spec:
      serviceAccountName: keycloak-writer-sa
      containers:
        - name: keycloak-post-grafana-container
          env:
            - name: NAMESPACE_PREFIX
              value: {{ .Values.config.namespacePrefix }}
            - name: PLATFORM_URL
              value: http://{{ .Values.config.namespacePrefix }}keycloak-keycloakx-http:8080
            - name: DOMAIN
              value: http://{{ .Values.config.domain }}
            - name: KEYCLOAK_USERNAME
              value: "admin"
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-initial-creds
                  key: password
            - name: GRAFANA_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-grafana-admin
                  key: username
            - name: GRAFANA_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-grafana-admin
                  key: password
          image: {{ .Values.config.postjobs.keycloakgrafana }}
          imagePullPolicy: Always
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.config.namespacePrefix }}keycloak-post-mcp-gateway-registry-job
  namespace: {{ .Values.config.namespacePrefix }}keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/hook: Sync
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 120
  activeDeadlineSeconds: 600
  template:
    spec:
      serviceAccountName: keycloak-writer-sa
      containers:
        - name: keycloak-post-mcp-gateway-registry-container
          env:
            - name: NAMESPACE_PREFIX
              value: {{ .Values.config.namespacePrefix }}
            - name: PLATFORM_URL
              value: http://{{ .Values.config.namespacePrefix }}keycloak-keycloakx-http:8080
            - name: MCP_SUBDOMAIN
              value: {{ printf "http://mcp.%s" .Values.config.domain | quote }}
            - name: KEYCLOAK_USERNAME
              value: "admin"
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-initial-creds
                  key: password
            - name: MCP_GATEWAY_REGISTRY_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-mcp-gateway-registry-admin
                  key: username
            - name: MCP_GATEWAY_REGISTRY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-mcp-gateway-registry-admin
                  key: password
          image: {{ .Values.config.postjobs.keycloakMcpGatewayRegistry }}
          imagePullPolicy: Always
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.config.namespacePrefix }}keycloak-post-argo-workflows-job
  namespace: {{ .Values.config.namespacePrefix }}keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/hook: Sync
spec:
  backoffLimit: 5
  ttlSecondsAfterFinished: 3600
  activeDeadlineSeconds: 600
  template:
    spec:
      serviceAccountName: keycloak-writer-sa
      containers:
        - name: keycloak-post-argo-workflows-container
          env:
            - name: NAMESPACE_PREFIX
              value: {{ .Values.config.namespacePrefix }}
            - name: PLATFORM_URL
              value: http://{{ .Values.config.namespacePrefix }}keycloak-keycloakx-http:8080
            - name: DOMAIN
              value: http://{{ .Values.config.domain }}
            - name: KEYCLOAK_USERNAME
              value: "admin"
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-initial-creds
                  key: password
          image: {{ .Values.config.postjobs.keycloakArgoWorkflows }}
          imagePullPolicy: Always
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.config.namespacePrefix }}keycloak-post-horizon-api-job
  namespace: {{ .Values.config.namespacePrefix }}keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/hook: Sync
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 120
  activeDeadlineSeconds: 600
  template:
    spec:
      serviceAccountName: keycloak-writer-sa
      containers:
        - name: keycloak-post-horizon-api-container
          env:
            - name: NAMESPACE_PREFIX
              value: {{ .Values.config.namespacePrefix }}
            - name: PLATFORM_URL
              value: http://{{ .Values.config.namespacePrefix }}keycloak-keycloakx-http:8080
            - name: DOMAIN
              value: http://{{ .Values.config.domain }}
            - name: KEYCLOAK_USERNAME
              value: "admin"
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-initial-creds
                  key: password
          image: {{ .Values.config.postjobs.keycloakhorizonapi }}
          imagePullPolicy: Always
      restartPolicy: Never